# Generated by Django 2.2.5 on 2019-09-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
