# Generated by Django 2.2.5 on 2019-09-14 06:17

from django.db import migrations, models
import revise.models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0002_utili'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=revise.models.upload_location, width_field='width_field'),
        ),
    ]
